name: Tests

on:
  push:
    branches: [master, main]
  pull_request:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shell:
    uses: cgraf78/actions/.github/workflows/shell-ci.yml@f9a9074b2d43fb3812067477d29307ef1e84e70e
    with:
      matrix-set: full
      profiles: base,jq,python,zsh
      shellcheck-inventory-path: .github/shellcheck-files.txt
      test-command: SLEY_SKIP_SHELLCHECK=1 test/sley-test
