name: Tests

on:
  push:
    branches: [master, main]
  pull_request:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shell:
    uses: cgraf78/actions/.github/workflows/shell-ci.yml@6258122bd79dc9296b5d529c33fc3aad8f4d5796
    with:
      matrix-set: full
      profiles: base,jq,python,zsh
      shellcheck-inventory-path: .github/shellcheck-files.txt
      test-command: SLEY_SKIP_SHELLCHECK=1 test/sley-test
